export const shadowUrl = "https://raw.githubusercontent.com/anushka2911/lucciano-images/master/uploads/shadow.png";
export const biteUrl = "https://raw.githubusercontent.com/anushka2911/lucciano-images/master/uploads/mordido.png";

// icePops Data
export const icePopDetails = [
  {
    iceCreamName: "Vanilla Delight",
    productDescription: "Classic vanilla ice cream",
    imageLink: "https://raw.githubusercontent.com/anushka2911/lucciano-images/master/uploads/passion%20fruit.png",
    price: 400,
    elementColor: "#E8C34D",
  },
  {
    iceCreamName: "Chocolate Dream",
    productDescription: "Smooth chocolate indulgence",
    imageLink: "https://raw.githubusercontent.com/anushka2911/lucciano-images/master/uploads/file-1604353227684.png",
    price: 500,
    elementColor: "#ccafa2",
  },
  {
    iceCreamName: "Strawberry Bliss",
    productDescription: "Sweet strawberry delight",
    imageLink: "https://raw.githubusercontent.com/anushka2911/lucciano-images/master/uploads/strawberry.png",
    price: 600,
    elementColor: "#ffb1ab",
  },
  {
    iceCreamName: "Cookies & Cream",
    productDescription: "Crunchy cookie bits",
    imageLink: "https://raw.githubusercontent.com/anushka2911/lucciano-images/master/uploads/file-1605797845032.png",
    price: 200,
    elementColor: "#f6dfb5",
  },
  {
    iceCreamName: "Mint Chocolate Chip",
    productDescription: "Minty chocolate chip",
    imageLink: "https://raw.githubusercontent.com/anushka2911/lucciano-images/master/uploads/chocolate%20toffee.png",
    price: 499,
    elementColor: "#f1d9b2",
  },
  {
    iceCreamName: "Vanilla Road",
    productDescription: "Vanilla and nuts",
    imageLink: "https://raw.githubusercontent.com/anushka2911/lucciano-images/master/uploads/mango.png",
    price: 299,
    elementColor: "#E5A74E",
  },
  {
    iceCreamName: "Caramel Strawberry Swirl",
    productDescription: "Caramel swirls",
    imageLink: "https://raw.githubusercontent.com/anushka2911/lucciano-images/master/uploads/file-1605797665503.png",
    price: 399,
    elementColor: "#caa7a2",
  },
  {
    iceCreamName: "Pistachio Perfection",
    productDescription: "Rich pistachio flavor",
    imageLink: "https://raw.githubusercontent.com/anushka2911/lucciano-images/master/uploads/file-1605797452923.png",
    price: 199,
    elementColor: "#f2e7d7",
  },
  {
    iceCreamName: "Rainbow Sherbet",
    productDescription: "Fruity and colorful sherbet",
    imageLink: "https://raw.githubusercontent.com/anushka2911/lucciano-images/master/uploads/file-1604348386314.png",
    price: 299,
    elementColor: "#f2e7d7",
  },
  {
    iceCreamName: "Coffee Caramel Crunch",
    productDescription: "Caffeine-infused delight",
    imageLink: "https://raw.githubusercontent.com/anushka2911/lucciano-images/master/uploads/file-1640786218937.png",
    price: 399,
    elementColor: "#f8c3c6",
  },
  {
    iceCreamName: "Lemon Sorbet",
    productDescription: "Sweet and tangy lemon",
    imageLink: "https://raw.githubusercontent.com/anushka2911/lucciano-images/master/uploads/lemon.png",
    price: 499,
    elementColor: "#e6dbce",
  },
  {
    iceCreamName: "Creamy Ripple",
    productDescription: "Creamy vanilla with blueberry",
    imageLink: "https://raw.githubusercontent.com/anushka2911/lucciano-images/master/uploads/file-1604356660438.png",
    price: 688,
    elementColor: "#fdd77a",
  },
  {
    iceCreamName: "Toffee Crunch",
    productDescription: "Crunchy toffee pieces",
    imageLink: "https://raw.githubusercontent.com/anushka2911/lucciano-images/master/uploads/file-1651679732112.png",
    price: 245,
    elementColor: "#EFE2D5",
  },
  {
    iceCreamName: "Peach Tango",
    productDescription: "Tropical mango ice cream",
    imageLink: "https://raw.githubusercontent.com/anushka2911/lucciano-images/master/uploads/file-1605797507558.png",
    price: 399,
    elementColor: "#ecdad2",
  },
  {
    iceCreamName: "Butter Pecan",
    productDescription: "Buttery ice cream with pecans",
    imageLink: "https://raw.githubusercontent.com/anushka2911/lucciano-images/master/uploads/file-1604351849637.png",
    price: 434,
    elementColor: "#edd5b3",
  },
  {
    iceCreamName: "Chocolate Blast",
    productDescription: "Chocolate with blueberry bits",
    imageLink: "https://raw.githubusercontent.com/anushka2911/lucciano-images/master/uploads/file-1605797481494.png",
    price: 399,
    elementColor: "#dcc1b0",
  },
  {
    iceCreamName: "Fruit CheeseCake",
    productDescription: "Maple syrup ice cream with cheese",
    imageLink: "https://raw.githubusercontent.com/anushka2911/lucciano-images/master/uploads/passionfruit%20Cheesecake.png",
    price: 289,
    elementColor: "#FFD652"
  },
];

// Gelato Data
export const gelatoData = [
  {
    icecreamName: "Fresa Delight",
    productDescription: "Dulce perfecto para el verano.",
    imageLink: "https://raw.githubusercontent.com/anushka2911/lucciano-images/master/uploads/file-1605796102869.png",
    price: "Rs. 150",
    color: "#fbccc6",
  },
  {
    icecreamName: "Pineapple Glacé",
    productDescription: "Un café suave y delicioso.",
    imageLink: "https://raw.githubusercontent.com/anushka2911/lucciano-images/master/uploads/file-1610718793008%20(1).png",
    price: "Rs. 120",
    color: "#ffd09d",
  },
  {
    icecreamName: "Vanilla Elegante",
    productDescription: "La  simplemente elegante.",
    imageLink: "https://raw.githubusercontent.com/anushka2911/lucciano-images/master/uploads/file-1605796064430.png",
    price: "Rs. 100",
    color: "#e8ab88",
  },
  {
    icecreamName: "Pistachio Fresco",
    productDescription: "Sabor a pista fresco tropical.",
    imageLink: "https://raw.githubusercontent.com/anushka2911/lucciano-images/master/uploads/file-1608320787259.png",
    price: "Rs. 130",
    color: "#e1d987",
  },
  {
    icecreamName: "Oreo Ricas",
    productDescription: "Rico, con toques de frambuesa.",
    imageLink: "https://raw.githubusercontent.com/anushka2911/lucciano-images/master/uploads/file-1608320456151.png",
    price: "Rs. 160",
    color: "#fdddc7",
  },
  {
    icecreamName: "Choco Tentación",
    productDescription: "Puro chocolate,  tentador.",
    imageLink: "https://raw.githubusercontent.com/anushka2911/lucciano-images/master/uploads/dark%20chocolate.png",
    price: "Rs. 180",
    color: "#be8671",
  },
  {
    icecreamName: "Caramelo Suave",
    productDescription: "Dulce caramelo delicia suave.",
    imageLink: "https://raw.githubusercontent.com/anushka2911/lucciano-images/master/uploads/file-1605795746859.png",
    price: "Rs. 140",
    color: "#e8ab88",
  },
  {
    icecreamName: "Lemon Cremosa",
    productDescription: "Crema de  toque de crocante.",
    imageLink: "https://raw.githubusercontent.com/anushka2911/lucciano-images/master/uploads/file-1610718218332.png",
    price: "Rs. 200",
    color: "#e1d987",
  },
  {
    icecreamName: "Plátano Vanilla",
    productDescription: "Sorprendente  de plátano.",
    imageLink: "https://raw.githubusercontent.com/anushka2911/lucciano-images/master/uploads/file-1610718319660.png",
    price: "Rs. 170",
    color: "#ffe486",
  },
  {
    icecreamName: "Coco Tropical",
    productDescription: "Sabor viaje tropical.",
    imageLink: "https://raw.githubusercontent.com/anushka2911/lucciano-images/master/uploads/file-1610721193651.png",
    price: "Rs. 160",
    color: "#fbccc6",
  },
  {
    icecreamName: "Almond Frescura",
    productDescription: "Refrescante  de limón.",
    imageLink: "https://raw.githubusercontent.com/anushka2911/lucciano-images/master/uploads/file-1649364848105.png",
    price: "Rs. 130",
    color: "#f8ecd9",
  },
  {
    icecreamName: "Choco Delicia",
    productDescription: "Delicia vellana, un placer cremoso.",
    imageLink: "https://raw.githubusercontent.com/anushka2911/lucciano-images/master/uploads/file-1610722888238.png",
    price: "Rs. 190",
    color: "#fcc480",
  },
  {
    icecreamName: "Menta Berry",
    productDescription: "Frescura  en cada cucharada.",
    imageLink: "https://raw.githubusercontent.com/anushka2911/lucciano-images/master/uploads/file-1651673902087.png",
    price: "Rs. 150",
    color: "#ffc9bc",
  },
  {
    icecreamName: "Maracuyá Pasión",
    productDescription: "La en un postre.",
    imageLink: "https://raw.githubusercontent.com/anushka2911/lucciano-images/master/uploads/file-1649365068727.png",
    price: "Rs. 170",
    color: "#fcc480",
  },
  {
    icecreamName: "Darko Perfecto",
    productDescription: "El  forma más perfecta.",
    imageLink: "https://raw.githubusercontent.com/anushka2911/lucciano-images/master/uploads/file-1651675957640.png",
    price: "Rs. 160",
    color: "#9d786c",
  },
  {
    icecreamName: "Almond Especial",
    productDescription: "Un toque  y sabor.",
    imageLink: "https://raw.githubusercontent.com/anushka2911/lucciano-images/master/uploads/file-1651840560634.png",
    price: "Rs. 140",
    color: "#DEA172",
  },
  {
    icecreamName: "Dulce de Leche",
    productDescription: "El  del dulce de leche.",
    imageLink: "https://raw.githubusercontent.com/anushka2911/lucciano-images/master/uploads/file-1605796102869.png",
    price: "Rs. 150",
    color: "#fbccc6",
  },
  
  {
    icecreamName: "Mango Delicioso",
    productDescription: "Simplemente  sabor a mango.",
    imageLink: "https://raw.githubusercontent.com/anushka2911/lucciano-images/master/uploads/file-1610718793008.png",
    price: "Rs. 130",
    color: "#ffd09d",
  },

];


